# Site settings
title: CocoaHeads Boston
description: > # this means to ignore newlines until "baseurl:"
  CocoaHeads Boston is a monthly meetup of developers for Apple's platforms. All are welcome.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://cocoaheadsboston.github.io" # the base hostname & protocol for your site
twitter_username: cocoaboston
collections:
  meetingnotes:
    output: true
    template: page
    permalink: /meeting-notes/:title/


defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
  -
    scope:
      path: ""
      type: "meetingnotes"
    values:
      layout: "meetingnotes"
