# Site settings
title: CocoaHeads Boston -- THIS IS NOT A LIVE SITE
description: > # this means to ignore newlines until "baseurl:"
  A meetup of Mac and iOS developers. We meet at 7:00 PM on the second Thursday of every month at MIT.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://cocoaheadsboston.github.io" # the base hostname & protocol for your site
twitter_username: cocoaboston
collections:
  meetingnotes:
    output: true
    template: page
    permalink: /meeting-notes/:title/


defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
  -
    scope:
      path: ""
      type: "meetingnotes"
    values:
      layout: "meetingnotes"
